# Generated by Django 5.0.6 on 2024-07-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='profile/'),
        ),
    ]
