# Generated by Django 5.0.6 on 2024-06-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_create',
            new_name='created_at',
        ),
    ]
